import { User } from './user';

export class UserData {
  static users: User[] = [
    {
      id: 1,
      firstName: 'Sean',
      lastName: 'Tyson',
      userTypeId: 2,
      age: 29,
      gender: 'Male',
      email: 'seantyson07@gmail.com',
      phoneNumbers: ['612-798-4111', '615-983-4873'],
      addressIds: [1],
    },
    {
      id: 2,
      firstName: 'Victor',
      middleInitial: 'D',
      lastName: 'Johnson',
      userTypeId: 1,
      age: 29,
      gender: 'Male',
      email: 'victordjohnson@gmail.com',
      phoneNumbers: ['763-355-8812'],
      addressIds: [2, 3],
    },
    {
      id: 3,
      firstName: 'Pete',
      middleInitial: 'D',
      lastName: 'Johnson',
      userTypeId: 1,
      age: 65,
      gender: 'Male',
      email: 'pete4938@gmail.com',
      phoneNumbers: ['612-568-1278'],
      addressIds: [3],
    },
    {
      id: 4,
      firstName: 'Mike',
      middleInitial: 'G',
      lastName: 'Riehm',
      userTypeId: 1,
      age: 26,
      gender: 'Male',
      email: 'MikeyBoi@gmail.com',
      phoneNumbers: ['612-798-4111', '615-983-4873'],
      addressIds: [1],
    },
    {
      id: 5,
      firstName: 'Tera',
      middleInitial: 'M',
      lastName: 'DeCavalacante',
      userTypeId: 2,
      age: 28,
      gender: 'Female',
      email: 'TeraD@gmail.com',
      phoneNumbers: ['612-916-7281'],
      addressIds: [4, 1],
    },
    {
      id: 6,
      firstName: 'Christine',
      middleInitial: 'M',
      lastName: 'Spain',
      userTypeId: 1,
      age: 28,
      gender: 'Female',
      email: 'ChristineSpain@gmail.com',
      phoneNumbers: ['612-561-9812'],
      addressIds: [5],
    },
  ];
}
